---
all:
  children:
    lab_vms:
      hosts:
        lab-ctrl01:
          ansible_host: 192.168.100.11
        lab-ctrl02:
          ansible_host: 192.168.100.12
        lab-ctrl03:
          ansible_host: 192.168.100.13
        lab-comp04:
          ansible_host: 192.168.100.14
        lab-comp05:
          ansible_host: 192.168.100.15
      vars:
        ansible_user: ubuntu
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    lab_control:
      hosts:
        lab-ctrl01:
        lab-ctrl02:
        lab-ctrl03:

    lab_compute:
      hosts:
        lab-comp04:
        lab-comp05:

    hypervisor:
      hosts:
        localhost:
          ansible_connection: local
